### ISSUE TITLE
Deleting and selecting images on iOS

### ISSUE THREAD

**Issue by ashneeldas2** [Get-Your-GreenBack-Tompkins/gygb-ios#5]
Todo 

- [x] Create view after picture is taken to select photos to send
- [X] Create view to choose whether user wants to save or delete photo

Acceptance Criteria
- [X] Users can choose photos to send
- [x] Users can discard photos they do not want
- [x] Matches current design
- [X] Users can take multiple photos

**Comment by ewlsh** [comment]
@ashneeldas2 @imanichilongani

- Deletion is not complete
- UI Design needs to move closer to the actual design.

**Comment by ewlsh** [comment]
Addressed in #7.

Punted: @ashneeldas2 Add an actual "delete" button to image corner.
